"""Wynnav's icon and banner: a crimson hall banner with a gold compass rose, and the name on a
matching cloth banner. Pixel art in a medieval palette; generated by art/pixelart.py."""
import math


PAL = {
    ".": None,
    "K": (0x14, 0x0E, 0x0A),  # outline (warm black)
    # gold
    "1": (0xFF, 0xF1, 0xA8), "2": (0xF6, 0xC8, 0x4C), "3": (0xC8, 0x8A, 0x24), "4": (0x8A, 0x55, 0x14),
    # iron / stone
    "a": (0xD6, 0xDA, 0xDE), "b": (0x9C, 0xA4, 0xAE), "c": (0x6A, 0x72, 0x7E), "d": (0x40, 0x46, 0x52),
    # oak
    "w": (0xB0, 0x74, 0x3E), "x": (0x82, 0x50, 0x28), "z": (0x55, 0x33, 0x1A),
    # crimson
    "r": (0xE0, 0x4A, 0x46), "s": (0xA8, 0x28, 0x30), "t": (0x6C, 0x16, 0x20),
    # royal blue
    "B": (0x4E, 0x7E, 0xD8), "C": (0x2C, 0x4E, 0xA0), "D": (0x1A, 0x2C, 0x64),
    # emerald (Wynncraft's currency)
    "e": (0x9C, 0xF6, 0xB0), "f": (0x3C, 0xD0, 0x6C), "g": (0x1C, 0x8C, 0x44), "h": (0x0C, 0x52, 0x28),
    # parchment
    "P": (0xF6, 0xE6, 0xC0), "Q": (0xE0, 0xC4, 0x8C), "R": (0xB8, 0x94, 0x5C), "S": (0x84, 0x64, 0x3A),
    # purple (magic)
    "m": (0xB4, 0x84, 0xF0), "n": (0x6E, 0x44, 0xB8),
    "W": (0xFF, 0xFF, 0xFF),
}


def canvas(w, h):
    return [["." for _ in range(w)] for _ in range(h)]


def put(g, x, y, c):
    if 0 <= y < len(g) and 0 <= x < len(g[0]):
        g[y][x] = c


def stamp(g, rows, ox, oy, skip="."):
    for j, row in enumerate(rows):
        for i, c in enumerate(row):
            if c != skip:
                put(g, ox + i, oy + j, c)


def outline(g, inside, color="K", diagonal=False):
    src = [r[:] for r in g]
    h, w = len(g), len(g[0])
    nb = [(1, 0), (-1, 0), (0, 1), (0, -1)] + ([(1, 1), (-1, -1), (1, -1), (-1, 1)] if diagonal else [])
    for y in range(h):
        for x in range(w):
            if src[y][x] == "." and any(0 <= x + dx < w and 0 <= y + dy < h and src[y + dy][x + dx] in inside for dx, dy in nb):
                g[y][x] = color


def mask_fill(mask, light, mid, dark, deep=None):
    """Bevelled fill of a boolean mask: top/left edges light, bottom/right edges dark."""
    h, w = len(mask), len(mask[0])
    out = canvas(w, h)
    on = lambda x, y: 0 <= x < w and 0 <= y < h and mask[y][x]
    for y in range(h):
        for x in range(w):
            if not mask[y][x]:
                continue
            top, left, bottom, right = on(x, y - 1), on(x - 1, y), on(x, y + 1), on(x + 1, y)
            if not top or not left:
                c = light
            elif not bottom or not right:
                c = dark
            else:
                c = mid
            out[y][x] = c
    return out


def compass_rose(size, long_len, long_w, short_len, short_w, light="1", dark="3", north=None, center="2"):
    """Compass rose: four long and four short diamond points, each split along its length into a
    light and a dark half (the classic map-rose look). `north` = (light, dark) recolours north."""
    n = size
    c = (n - 1) / 2
    g = canvas(n, n)
    points = [(0, -1, long_len, long_w), (1, 0, long_len, long_w), (0, 1, long_len, long_w), (-1, 0, long_len, long_w)]
    r = 1 / math.sqrt(2)
    points += [(r, -r, short_len, short_w), (r, r, short_len, short_w), (-r, r, short_len, short_w), (-r, -r, short_len, short_w)]
    for y in range(n):
        for x in range(n):
            dx, dy = x - c, y - c
            for k, (ux, uy, length, width) in enumerate(points):
                along = dx * ux + dy * uy
                across = dx * -uy + dy * ux  # >0 = clockwise side
                if 0 <= along <= length and abs(across) <= width * (1 - along / length) + 0.15:
                    is_north = k == 0
                    lit = across <= 0.05
                    if is_north and north:
                        col = north[0] if lit else north[1]
                    else:
                        col = light if lit else dark
                    # long points draw over short ones
                    if g[y][x] == "." or k < 4:
                        g[y][x] = col
                    break
    cc = int(c)
    g[cc][cc] = center
    return g


def icon():
    """A crimson heraldic banner hanging from a wooden pole, with a gold compass rose."""
    g = canvas(32, 32)
    # pole with gold finials
    for x in range(4, 28):
        g[3][x] = "w"; g[4][x] = "x"
    for cap in ((2, "2"), (3, "3"), (28, "2"), (29, "3")):
        g[3][cap[0]] = "1"; g[4][cap[0]] = cap[1]
    # cloth with swallowtail
    for y in range(5, 29):
        for x in range(7, 25):
            tail = y > 23 and (abs(x - 15.5) < (y - 23) * 1.1)
            if not tail:
                g[y][x] = "r" if x < 10 else "t" if x > 22 else "s"
    # gold trim along the sides and the tails
    for y in range(5, 29):
        for x in range(7, 25):
            if g[y][x] in ("r", "s", "t"):
                edge = any(not (0 <= x + dx < 32 and 0 <= y + dy < 32) or g[y + dy][x + dx] in (".", "w", "x")
                           for dx, dy in ((1, 0), (-1, 0), (0, 1)))
                if edge:
                    g[y][x] = "2" if x < 16 else "3"
    # emblem: gold compass star with an emerald center
    starfill = compass_rose(15, 7, 2.2, 4, 1.4, center="f")
    stamp(g, starfill, 8, 9)
    sub = canvas(32, 32)
    stamp(sub, starfill, 8, 9)
    for y in range(32):
        for x in range(32):
            if sub[y][x] == "." and g[y][x] in ("r", "s", "t"):
                if any(0 <= x + dx < 32 and 0 <= y + dy < 32 and sub[y + dy][x + dx] != "." for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))):
                    g[y][x] = "t"
    outline(g, set("rst123wx"))
    return g


GLYPHS = {
    "W": """
###.......###
.##.......##.
.##...#...##.
.##..###..##.
..##.###.##..
..##.#.#.##..
..##.#.#.##..
...###.###...
...###.###...
...##...##...
....#...#....
""",
    "y": """
###..###
.##...##
.##...##
..##.##.
..##.##.
...###..
...###..
...##...
...##...
..##....
####....
""",
    "n": """
###.##..
.###.##.
.##...##
.##...##
.##...##
.##...##
.##...##
###..###
""",
    "a": """
.#####..
##...##.
.....##.
.######.
##...##.
##...##.
##..###.
.###.###
""",
    "v": """
###..###
.##...##
.##...##
..##.##.
..##.##.
...###..
...###..
....#...
""",
}


def glyph(ch):
    rows = [r for r in GLYPHS[ch].strip("\n").split("\n")]
    return [[c == "#" for c in r] for r in rows]


def word_mask(text, spacing=1):
    cap = 11
    glyphs = [glyph(ch) for ch in text]
    width = sum(len(gl[0]) for gl in glyphs) + spacing * (len(glyphs) - 1)
    height = cap + 3
    m = [[False] * width for _ in range(height)]
    x = 0
    for ch, gl in zip(text, glyphs):
        top = 0 if ch.isupper() else cap - 8
        for j, row in enumerate(gl):
            for i, on in enumerate(row):
                if on:
                    m[top + j][x + i] = True
        x += len(gl[0]) + spacing
    return m


def stamp_word(g, ox, oy, light, mid, dark, outline_color="K", shadow=None):
    m = word_mask("Wynnav")
    letters = mask_fill(m, light, mid, dark)
    if shadow:
        sh = [[shadow if v else "." for v in row] for row in m]
        stamp(g, sh, ox + 1, oy + 1)
    stamp(g, letters, ox, oy)
    # outline only around the letters
    sub = canvas(len(g[0]), len(g))
    stamp(sub, letters, ox, oy)
    for y in range(len(g)):
        for x in range(len(g[0])):
            if sub[y][x] == "." and any(0 <= x + dx < len(g[0]) and 0 <= y + dy < len(g) and sub[y + dy][x + dx] != "."
                                        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))):
                g[y][x] = outline_color
    return len(m[0]), len(m)


def banner():
    """A crimson cloth banner hanging from an oak beam, gold trim and gold letters."""
    W, H = 92, 34
    g = canvas(W, H)
    # beam
    for x in range(1, 91):
        g[2][x] = "w"; g[3][x] = "x"; g[4][x] = "z"
    for cap in (0, 1, 90, 91):
        if 0 <= cap < W:
            g[2][cap] = "1"; g[3][cap] = "2"; g[4][cap] = "3"
    # rings holding the cloth
    for rx in (12, 32, 59, 79):
        g[5][rx] = "c"; g[6][rx] = "b"
    # cloth with a scalloped bottom
    for y in range(6, 31):
        for x in range(6, 86):
            scallop = y > 26 and ((x - 6) % 10 in (0, 9) or (y > 28 and (x - 6) % 10 not in (4, 5)))
            if not scallop:
                g[y][x] = "r" if y < 9 else "s"
    # gold trim
    for x in range(6, 86):
        if g[7][x] != ".":
            g[7][x] = "2"
    for y in range(6, 31):
        for x in range(6, 86):
            if g[y][x] in ("r", "s"):
                if any(g[y + dy][x + dx] == "." for dx, dy in ((1, 0), (-1, 0), (0, 1)) if 0 <= y + dy < H and 0 <= x + dx < W):
                    g[y][x] = "3"
    # vertical folds
    for fx in (22, 46, 70):
        for y in range(8, 28):
            if g[y][fx] == "s":
                g[y][fx] = "t"
    outline(g, set("rst23wxz1bc"))
    m = word_mask("Wynnav")
    stamp_word(g, (W - len(m[0])) // 2, 11, "1", "2", "3", outline_color="K", shadow="t")
    return g


def colors(g):
    return [[PAL[c] for c in row] for row in g]
